package com.rcslabs.webcall;

public enum MessageType {

    START_SESSION,
    SESSION_STARTED,
    SESSION_FAILED,
    CLOSE_SESSION,
    SESSION_CLOSED,

    START_CALL,
    INCOMING_CALL,
    REJECT_CALL,
    ACCEPT_CALL,
    HANGUP_CALL,
    CALL_STARTING,
    CALL_STARTED,
    CALL_FAILED,
    CALL_FINISHED,
    CALL_FINISH_NOTIFICATION, // TODO: move this out

    SEND_DTMF,
    SEND_MESSAGE,

    SDP_OFFER,
    SDP_ANSWER,

    CREATE_MEDIA_POINT,
    CREATE_MEDIA_POINT_OK,
    CREATE_MEDIA_POINT_FAILED,

    REMOVE_MEDIA_POINT,
    REMOVE_MEDIA_POINT_OK,
    REMOVE_MEDIA_POINT_FAILED,

    JOIN_ROOM,
    JOIN_OK,
    JOIN_FAILED,

    UNJOIN_ROOM,
    UNJOIN_OK,
    UNJOIN_FAILED,

    CRITICAL_ERROR ;
}
